defaults: &defaults
  working_directory: /tmp/cci-test
version: 2
jobs:
  s1:
    <<: *defaults
    docker:
      - image: golang:latest
    steps:
      - checkout
      - run: pwd
      - run:
          name: set var
          command: echo "export s1_CIRCLE_BUILD_NUM=$CIRCLE_BUILD_NUM" >> $BASH_ENV
      - run: echo "$s1_CIRCLE_BUILD_NUM"
      - run: mkdir -p workspace
      - run: echo "export s1_CIRCLE_BUILD_NUM=$CIRCLE_BUILD_NUM" >> workspace/new-env-vars
      - run: cat workspace/new-env-vars >> $BASH_ENV
      - persist_to_workspace:
          root: workspace
          paths:
              - new-env-vars
  s2:
    <<: *defaults
    docker:
      - image: golang:latest
    steps:
      - attach_workspace:
          at: /tmp/cci-test/workspace
      - run: cat workspace/new-env-vars >> $BASH_ENV
      - run: echo "This is running in the second job"
      - run: ls -l
      - run:
          name: Print s1_CIRCLE_BUILD_NUM
          commands: |
            echo "s1_CIRCLE_BUILD_NUM: ${s1_CIRCLE_BUILD_NUM}""

workflows:
  version: 2
  example_jobs:
    jobs:
      - s1
      - s2:
          requires:
            - s1
